### ISSUE TITLE
Tobacco use codes

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/allostatic_loadtest#1]
Any of the following strings in the tobacco column identify a patient who uses tobacco:
`TOBACCO_USER:1` , `SMOKING_TOB_USE:1` , `SMOKING_TOB_USE:2` , `SMOKING_TOB_USE:3` , `SMOKING_TOB_USE:9` , `SMOKING_TOB_USE:10` , `SMOKELESS_TOB_USE:1`
Possible (not tested) grep pattern: `TOBACCO_USER:1|SMOKING_TOB_USE:[1239]|SMOKELESS_TOB_USE:1`

Any of the following strings identify former users (logically, if they co-occur with above, the above should take priority for that visit):
`TOBACCO_USER:4` , `SMOKING_TOB_USE:4`, `SMOKELESS_TOB_USE:2`
Possible (not tested) grep pattern: `TOBACCO_USER:4|SMOKING_TOB_USE:4|SMOKELESS_TOB_USE:2`

Any of the following strings identify passive exposure (again, the above take precedence in the order they appear):
`TOBACCO_USER:5` , `SMOKING_TOB_USE:7`
Possible (not tested) grep pattern: `TOBACCO_USER:5|SMOKING_TOB_USE:7`

Any of the following strings identify explicitly people who never used tobacco products (above take precedence in order they appear):
`TOBACCO_USER:2` , `SMOKING_TOB_USE:5`, `SMOKELESS_TOB_USE:3`
Possible (not tested) grep pattern: `TOBACCO_USER:2|SMOKING_TOB_USE:5|SMOKELESS_TOB_USE:3`

If none of the above are present, then any of the following or missing values imply unknown status:
`TOBACCO_USER:3`, `SMOKING_TOB_USE:6`, `SMOKING_TOB_USE:8`, `SMOKELESS_TOB_USE:4`.

I suggest either...
- Adding one new column that is `T` if they are a current user, `F` if non-user/quit/passive, and `NA` if completely unknown
- A separate column each for smoker, passive, and quit... true non-smokers would have `F` in all three columns, and when all information is missing they would have `NA`

Not sure if we need to worry about the packs-per-day, years of usage, and quit-dates. Might want to see if these crude levels have an effect or are close enough to having an effect as to justify digging deeper.

**Comment by bokov** [comment]
What we don't yet know:
- Do contradictory combinations of codes occur? (e.g. non-smoker and heavy smoker)
- Does the actual value show up, perhaps in the _INFO column, for: number of years, packs per day, or quit dates?
- Are quit dates, number of years, and packs per day always accompanied by the tobacco codes they imply on the same visit?
- Conversely, are tobacco codes that imply an accompanying value always accompanied by such a value during the same visit?
- Are tobacco codes recorded once per visit or once per patient?
- Are tobacco codes mostly stable from one visit to the next, and when they do change, is it in a way that seems plausible in the real world?
- Are there any patients completely lacking tobacco codes?

**Comment by Vivek-Prakash-US** [comment]
Look into if "packs per day" have a numeric value.

**Comment by bokov** [comment]
We gave up and went with re-pulling the data, this time with smoking codes in separate columns. Databuilder completed, DataFinisher fell over with a new bug. The bug is in a user-defined SQLite function returning an error. This is a new one, those things have been stable for quite a while until today. I suspect the string condensing functions are where it is happening. Currently the following are my leading theories:
- The bug was introduced by recent changes, so I'll try checking out an earlier snapshot and see if that one runs successfully (or at least errors further into the script).
- The bug is unmasked by something about the tobacco columns. We have not looked at them closely before.

**Comment by bokov** [comment]
Note: this does not have to hold up most of the tasks (except #4 and maybe, arguably, #2 ). The rest of them you can work on just fine with the existing, jumbled-tobacco data file because the R code you write will be just as valid for the new version of the data file.
